{% set name = "pynco" %}
{% set version = "1.0.0" %}
{% set sha256 = "7949fabe691ae7da3d9b9331b0983e815713636c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nco/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [py<35]

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - nco

about:
  home: https://github.com/nco/pynco
  license: MIT
  license_file: LICENSE.txt
  summary: 'Python bindings to NCO.'

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - kwilcox
