{% set name = "pynco" %}
{% set package_name = "nco" %}
{% set version = "1.1.2" %}
{% set build_num = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ package_name[0] }}/{{ package_name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 2a9468662a4f4fc4505162a205ae54b4da375bdce567fd3649f7f614272b79d5

build:
  number: {{ build_num }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - nco
    - numpy
    - packaging

test:
  imports:
    - nco

about:
  home: https://github.com/nco/pynco
  license: MIT
  license_file: LICENSE.txt
  summary: 'Python bindings to NCO.'

extra:
  recipe-maintainers:
    - czender
    - mx-moth
    - jhamman
    - ocefpaf
    - kwilcox
    - czender
    - mx-moth
