{% set name = "pynco" %}
{% set package_name = "nco" %}
{% set version = "1.0.0" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ package_name[0] }}/{{ package_name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 58c06800f35a54dcde0e74a089788c3a90622dffbd125b478005c18612137fb0

build:
  number: {{ build_num }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - nco
    - numpy

test:
  imports:
    - nco

about:
  home: https://github.com/nco/pynco
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: 'Python bindings to NCO.'

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - kwilcox
    - czender
    - mx-moth
