{% set version = "1.0.0" %}

package:
  name: pynco
  version: {{ version }}

source:
  url: https://github.com/nco/pynco/archive/{{ version }}.tar.gz
  sha256: b82c02d9bb2bd8ee9747d7f1a24e5fe1476c75f956f16cb88805f1cc8eff5dd2

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - nco
    - numpy

test:
  imports:
    - nco

about:
  home: https://github.com/nco/pynco
  license: GPL-2.0
  license_file: LICENSE.txt
  summary: 'Python bindings to NCO.'

extra:
  recipe-maintainers:
    - czender
    - jhamman
    - ocefpaf
    - kwilcox
