travis:
  secure:
    BINSTAR_TOKEN: Ko+e+WMM+4AuQGJjJIXStFsFLHjKSJLKSkkLiSEqCDOc5NEgkQhwSli87Q3IKUA9zYB44l79wMMI23vkqJ+b5w5oUVI8it+iLTAF12PTUuLnvrqsQp31UiPp8L7nQaK3kvitUOGc9rlomfAGcxp7rAYCSeqApcAGZVCvNrfeHNPeJEA20m5GoFth0GALTgSFBuGWazSahCBLYvdyKS3RGUXELhT+yeeGCECM8YGg72QPPrTm/R062Aqfe3/GjssVjESIIvpzsx5/45x4+hcEPjqjug7PFcxgsnHLTQWXHIgkqV+LtVoeTj7kgUFS1rjlM7pfKrafARVAROQpapTEu78Y9dSShtJTCHzrFgob+qcFRHEjTcPl3xFK1XJnBgvHAEktK0vuIIp23V51xwTQcCEYr2xb4hOjNyrWGE2hHKj1q7MKsl4hFPL0wfTIn3PU9AVtKyEs8tl+nfMF330bhClDNsIqAbOlDSUsZtRkQgliRqALIj+Q+N2pNAJMHCa/v/uYe5bnljf6v4Ux0YoGvvN/q6i3WvM7zHgm9zwkYlgdPt8J+F5WDzz0ANx8YrDKK5KBdBSaA0F+wmq8sreQ4y8tqOHt9YKsORssiCpv0/Ar1/O11dcsuJHXHaElXOGbQHFUyRoJCVb0A7RvucZPGuz97idorQFbGIcMYnpzNho=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
