travis:
  secure:
    BINSTAR_TOKEN: TBFlWO2xAI2I3bQ0uhY65Zwj003tuXCWGrpBoQEt45wB5c4H9LhBnUYW26sHcbn9cbiwABtO9u3b5D4Dp1SzbtDnlnEVRaYU1l8XYE1tHMoqfYsWXVYPCE4/LsKs9Y5ZSxz5ShQOq6kTYMzRu8BpTzSiCscVwhRMtsjxtzjXtrHdPd4Vx1JIvBX4irhTwMx3+D2wcUaorA7cQb4TanoOKHjmswjxM5WuDo7l2xs6MvgfbGQYwk0HZq1Ne+PsLuqklDNC99etK9esughNkvcC8HTx5lECsBcT0DtOmoJIxyQkCEheD2lxUGKekSUmg2Na1LVXGc69ZJ0nJcOtPVIWCqFrc2Bk6wF9KzJ6mZry8yGJNKVYW0y4kAnRNAYW1q45kQd6wmYdDzRjeaJnFxQDKnCHNUopkA0paYA6xYnpR2dtauJIB3m251zICMP6Eznm2NXWhQ7Tkoskrpy3Qe7PsGETCqxecdgAEn06pImMB67gwI9XaNP7ewpTjHik+SKA+0WvlTTXm+b338cLp5Jr5St9PMmOCugGGiFHb2eb727NLCX7l4c+Qk1D8Hjtvn6rVGX31wZc0NuJW3krMtoYwIEvWoT3caDhnvz8OV01febprRJhq3ne/Hcp5SHz2mjjFNqR33fiqwNej96I6uoj5fU2jVf03jziKsiwfkOnnl8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
